spring:
  application:
    name: gateway-service
  config:
    import: optional:configserver:""
  cloud:
    gateway:
      mvc:
        routes:
          - id: students
            uri: http://localhost:9090
            predicates:
              -  Path=/post/**
          - id : courses
            uri: http://localhost:8090
            predicates:
              - Path=/comment/**
          - id: courses
            uri: http://localhost:8087
            predicates:
              - Path=/user/**


